[phases.setup]
nixPkgs = ["chromium", "chromium-sandbox", "nss", "atk", "atk-bridge", "gtk3", "gdk-pixbuf2", "pango", "cairo", "gdk-pixbuf2", "libX11", "libXcomposite", "libXcursor", "libXdamage", "libXext", "libXi", "libXtst", "cups-libs", "libXScrnSaver", "libXrandr", "alsa-lib"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser" 