-- Conta Google de serviço (ex.: zelar.ia.messages@gmail.com): OAuth tokens em JSON; convites quando o usuário não tem Google/Microsoft.
CREATE TABLE IF NOT EXISTS public.system_calendar_integrations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_key varchar(128) NOT NULL,
  provider varchar(32) NOT NULL,
  account_email text,
  tokens jsonb NOT NULL DEFAULT '{}'::jsonb,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT system_calendar_integrations_key_provider UNIQUE (integration_key, provider)
);

CREATE INDEX IF NOT EXISTS idx_system_calendar_integrations_key
  ON public.system_calendar_integrations (integration_key);
